
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import timeTable.TimeTable;
import timeTable.TimeTableDAO;
import user.User;
import user.UserDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author seungmin
 */
public class MainFrame extends javax.swing.JFrame {
    private int loggedInNo;
    private String loggedInId;
    private String loggedInName;
    private String[] startTime = {"9:00", "9:55", "10:50", "11:45", "12:40", "13:35", "14:30", "15:25", "16:20", "17:15", "18:10", "19:00", "19:50"};
    private String[] endTime = {"9:50", "10:45", "11:40", "12:35", "13:30", "14:25", "15:20", "16:15", "17:10", "18:05", "18:55", "19:45", "20:35"};
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jTabbedPane1.remove(jPanelTime);
        timeTableNo.setVisible(false);
        
        for(int i = 0; i < jTable1.getRowCount(); i++) {
            jTable1.setValueAt("<html>"+(i+1)+"교시<br>"+startTime[i]+"<br>"+endTime[i]+"</html>", i, 0);
        }
        
    }
    
    public boolean overlapChk() {
        boolean result = false;
        
        UserDAO userDAO = new UserDAO();
        String userId = txtRegId.getText();
        if(userId.equals("")){
            lblOverlap.setText("아이디를 입력해주세요.");
            return false;
        }
        
        if(userDAO.isOverlap(userId)) {
            lblOverlap.setText("중복된 아이디입니다.");
        } else {
            lblOverlap.setText("사용 가능한 아이디입니다.");
            result = true;
        }
        
        return result;
    }
    
    public boolean valueCheck(String value) {
        boolean result = true;
        if(value.isEmpty()) result = false;
        if(value.contains(" ")) result = false;
        
        return result;
    }
    
    public void loadTimeTable(ArrayList<TimeTable> arrList) {
        int rowCnt = jTable1.getRowCount();
        int colCnt = jTable1.getColumnCount();
        
        for(int i = 1; i < colCnt; i++) {
            for(int j = 0; j < rowCnt; j ++) {
                jTable1.setValueAt("", j, i);
            }
        }
        
        for(TimeTable tt : arrList) {
            String text = "<html>"+tt.getSubject() + "<br>" + tt.getProfessor() + "<br>" + tt.getClassroom()+"</html>";
            //String text = tt.getSubject();
            for(int i = tt.getStartTime(); i <= tt.getEndTime(); i++) {
                
                jTable1.setValueAt(text, i, tt.getDay());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtLoginId = new javax.swing.JTextField();
        lblPw = new javax.swing.JLabel();
        txtLoginPw = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelReg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        txtRegId = new javax.swing.JTextField();
        lblPw1 = new javax.swing.JLabel();
        lblPw2 = new javax.swing.JLabel();
        btnOverlap = new javax.swing.JButton();
        lblOverlap = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtRegName = new javax.swing.JTextField();
        txtRegPw = new javax.swing.JPasswordField();
        txtRegPwChk = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        jPanelTime = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddSubject = new javax.swing.JButton();
        lblTimeTableName = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        lblSubject = new javax.swing.JLabel();
        lblProp = new javax.swing.JLabel();
        txtProf = new javax.swing.JTextField();
        lblClassroom = new javax.swing.JLabel();
        txtClassroom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxDay = new javax.swing.JComboBox<>();
        cbxStartTime = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxEndTime = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnDeleteSubject = new javax.swing.JButton();
        btnModifySubject = new javax.swing.JButton();
        timeTableNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel3.setText("로그인");

        lblId.setText("아이디");

        lblPw.setText("비밀번호");

        btnLogin.setText("로그인");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(0, 335, Short.MAX_VALUE)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginLayout.createSequentialGroup()
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPw)
                                    .addComponent(lblId))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLoginId)
                                    .addComponent(txtLoginPw, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel3)))
                        .addGap(292, 292, 292))))
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPw)
                            .addComponent(txtLoginPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("로그인", jPanelLogin);

        jLabel4.setFont(new java.awt.Font("굴림", 1, 24)); // NOI18N
        jLabel4.setText("회원가입");

        lblId1.setText("아이디");

        lblPw1.setText("비밀번호");

        lblPw2.setText("비밀번호 확인");

        btnOverlap.setText("중복확인");
        btnOverlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverlapActionPerformed(evt);
            }
        });

        lblOverlap.setText("         ");

        lblName.setText("닉네임");

        btnRegister.setText("회원가입");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegLayout = new javax.swing.GroupLayout(jPanelReg);
        jPanelReg.setLayout(jPanelRegLayout);
        jPanelRegLayout.setHorizontalGroup(
            jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegLayout.createSequentialGroup()
                        .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelRegLayout.createSequentialGroup()
                                    .addComponent(lblName)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtRegName))
                                .addGroup(jPanelRegLayout.createSequentialGroup()
                                    .addComponent(lblId1)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRegId)
                                        .addComponent(lblOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelRegLayout.createSequentialGroup()
                                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPw1)
                                    .addComponent(lblPw2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRegPw, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRegPwChk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOverlap))
                    .addGroup(jPanelRegLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel4)))
                .addGap(301, 301, 301))
        );
        jPanelRegLayout.setVerticalGroup(
            jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblId1)
                        .addComponent(btnOverlap)))
                .addGap(13, 13, 13)
                .addComponent(lblOverlap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtRegName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegLayout.createSequentialGroup()
                        .addComponent(txtRegPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRegPwChk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRegLayout.createSequentialGroup()
                        .addComponent(lblPw1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPw2)))
                .addGap(37, 37, 37)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("회원가입", jPanelReg);

        btnLogout.setText("로그아웃");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "시간", "월", "화", "수", "목", "금"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(70);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        btnAddSubject.setText("수업추가");
        btnAddSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSubjectActionPerformed(evt);
            }
        });

        lblTimeTableName.setText("@@@님의 시간표");

        lblSubject.setText("수업명");

        lblProp.setText("교수명");

        lblClassroom.setText("장소");

        jLabel7.setText("요일");

        cbxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "월", "화", "수", "목", "금" }));

        cbxStartTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));

        jLabel8.setText("교시  ~");

        cbxEndTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));

        jLabel9.setText("교시");

        btnDeleteSubject.setText("수업삭제");
        btnDeleteSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSubjectActionPerformed(evt);
            }
        });

        btnModifySubject.setText("수업수정");
        btnModifySubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifySubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTimeLayout = new javax.swing.GroupLayout(jPanelTime);
        jPanelTime.setLayout(jPanelTimeLayout);
        jPanelTimeLayout.setHorizontalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(lblTimeTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cbxStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifySubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteSubject))
                    .addGroup(jPanelTimeLayout.createSequentialGroup()
                        .addComponent(lblSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblProp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClassroom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(timeTableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelTimeLayout.setVerticalGroup(
            jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout)
                    .addComponent(lblTimeTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubject)
                    .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProp)
                    .addComponent(txtClassroom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClassroom)
                    .addComponent(timeTableNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeleteSubject)
                        .addComponent(btnModifySubject)
                        .addComponent(btnAddSubject))
                    .addGroup(jPanelTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(cbxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(cbxStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(cbxEndTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("내 시간표", jPanelTime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        User user = new User();
        UserDAO userDAO = new UserDAO();
        
        String userId = txtRegId.getText();
        String userName = txtRegName.getText();
        String userPw = txtRegPw.getText();
        String userPwChk = txtRegPwChk.getText();
        
        if(!valueCheck(userId)) {
            JOptionPane.showMessageDialog(null, "아이디는 공백이거나 공백을 포함할 수 없습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!overlapChk()) return;
        
        if(!valueCheck(userName)) {
            JOptionPane.showMessageDialog(null, "닉네임은 공백이거나 공백을 포함할 수 없습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!valueCheck(userPw)) {
            JOptionPane.showMessageDialog(null, "비밀번호는 공백이거나 공백을 포함할 수 없습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        user.setUserId(userId);
        user.setUserName(userName);
        if(userPw.equals(userPwChk)) {
            user.setUserPw(userPw);
        } else {
            JOptionPane.showMessageDialog(null, "비밀번호가 일치하지 않습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(userDAO.register(user) == 1) {
            JOptionPane.showMessageDialog(null, "회원가입 되었습니다.");
            jTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "회원가입을 실패했습니다.", "경고", JOptionPane.ERROR_MESSAGE);
        }
        userDAO.dbClose();

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnOverlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverlapActionPerformed
        // TODO add your handling code here:
        overlapChk();
    }//GEN-LAST:event_btnOverlapActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String userId = txtLoginId.getText();
        String userPw = txtLoginPw.getText();
        
        UserDAO userDAO = new UserDAO();
        
        if(!valueCheck(userId)) {
            JOptionPane.showMessageDialog(null, "아이디를 입력해주세요.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!valueCheck(userPw)) {
            JOptionPane.showMessageDialog(null, "비밀번호를 입력해주세요.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        User result = userDAO.login(userId, userPw);
        if(result != null) {
            JOptionPane.showMessageDialog(null, "로그인 성공.");
            loggedInNo = result.getUserNo();
            loggedInId = result.getUserId();
            loggedInName = result.getUserName();
            jTabbedPane1.addTab("시간표", jPanelTime);
            lblTimeTableName.setText(loggedInName+"님의 시간표");
            TimeTableDAO ttDAO = new TimeTableDAO();
            loadTimeTable(ttDAO.getList(loggedInNo));
            jTabbedPane1.setSelectedIndex(2);
           
        } else {
            JOptionPane.showMessageDialog(null, "아이디 또는 비밀번호가 일치하지 않습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        userDAO.dbClose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnAddSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSubjectActionPerformed
        // TODO add your handling code here:
        TimeTable tt = new TimeTable();
        TimeTableDAO ttDAO = new TimeTableDAO();
        String subject = txtSubject.getText();
        String professor = txtProf.getText();
        String classroom = txtClassroom.getText();
        if(!valueCheck(subject) || !valueCheck(professor) || !valueCheck(classroom)) {
            JOptionPane.showMessageDialog(null, "빈 값은 입력할 수 없습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        tt.setSubject(subject);
        tt.setProfessor(professor);
        tt.setClassroom(classroom);
        tt.setDay(cbxDay.getSelectedIndex()+1);
        tt.setStartTime(cbxStartTime.getSelectedIndex());
        tt.setEndTime(cbxEndTime.getSelectedIndex());
        tt.setUserNo(loggedInNo);
       
        
        if(ttDAO.isOverlap(subject, loggedInNo) == 1) {
            JOptionPane.showMessageDialog(null, "이미 존재하는 교과목입니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(ttDAO.addSubject(tt) == 1){
            loadTimeTable(ttDAO.getList(loggedInNo));
            JOptionPane.showMessageDialog(null, "수업을 추가했습니다.");
        } else {
            JOptionPane.showMessageDialog(null, "수업을 추가하는데 오류가 발생했습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ttDAO.dbClose();
    }//GEN-LAST:event_btnAddSubjectActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        int column = source.columnAtPoint(evt.getPoint());
        String text = source.getModel().getValueAt(row,column)+"";
        System.out.println(text);
        if(column == 0) {
            return;
        }
        
        if(text.equals("null") || text.equals("")) {
            txtSubject.setText("");
            txtProf.setText("");
            txtClassroom.setText("");
            cbxDay.setSelectedIndex(0);
            cbxStartTime.setSelectedIndex(0);
            cbxEndTime.setSelectedIndex(0);
            timeTableNo.setText("-1");
            return;
        }
        String tmp = text.substring(6, text.length()-7);
        
        String[] arr = tmp.split("<br>");
        
        String subject = arr[0];
        String professor = arr[1];
        String classroom = arr[2];
        
        TimeTable tt = new TimeTable();
        tt.setSubject(subject);
        tt.setProfessor(professor);
        tt.setClassroom(classroom);
        
        TimeTable result = new TimeTableDAO().getOne(tt);
        
        txtSubject.setText(subject);
        txtProf.setText(professor);
        txtClassroom.setText(classroom);
        cbxDay.setSelectedIndex(result.getDay()-1);
        cbxStartTime.setSelectedIndex(result.getStartTime());
        cbxEndTime.setSelectedIndex(result.getEndTime());
        timeTableNo.setText(Integer.toString(result.getTimeNo()));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnModifySubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifySubjectActionPerformed
        // TODO add your handling code here:
        TimeTable tt = new TimeTable();
        TimeTableDAO ttDAO = new TimeTableDAO();
        String subject = txtSubject.getText();
        String professor = txtProf.getText();
        String classroom = txtClassroom.getText();
        int day = cbxDay.getSelectedIndex()+1;
        int startTime = cbxStartTime.getSelectedIndex();
        int endTime = cbxEndTime.getSelectedIndex();
        int timeNo = -1;
        
        try {
            timeNo = Integer.parseInt(timeTableNo.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "수업을 선택해주세요.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        if(!valueCheck(subject) || !valueCheck(professor) || !valueCheck(classroom)) {
            JOptionPane.showMessageDialog(null, "빈 값 또는 공백은 입력할 수 없습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        tt.setSubject(subject);
        tt.setProfessor(professor);
        tt.setClassroom(classroom);
        tt.setDay(day);
        tt.setStartTime(startTime);
        tt.setEndTime(endTime);
        tt.setTimeNo(timeNo);
        tt.setUserNo(loggedInNo);
        
        if(ttDAO.isOverlap(subject, loggedInNo, timeNo) == 1) {
            JOptionPane.showMessageDialog(null, "이미 존재하는 교과목입니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(ttDAO.update(tt)==1) {
            JOptionPane.showMessageDialog(null, "정보가 수정되었습니다.");
            loadTimeTable(ttDAO.getList(loggedInNo));
        } else {
            JOptionPane.showMessageDialog(null, "정보 수정을 실패했습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ttDAO.dbClose();
    }//GEN-LAST:event_btnModifySubjectActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        loggedInId = null;
        loggedInNo = -1;
        loggedInName = null;
        
        txtLoginId.setText("");
        txtLoginPw.setText("");
        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.remove(jPanelTime);
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDeleteSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSubjectActionPerformed
        // TODO add your handling code here:
        TimeTable tt = new TimeTable();
        TimeTableDAO ttDAO = new TimeTableDAO();
        int timeNo = -1;
        
        try {
            timeNo = Integer.parseInt(timeTableNo.getText());
            if(timeNo < 0) {
                JOptionPane.showMessageDialog(null, "수업을 선택해주세요.", "경고", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "수업을 선택해주세요.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        tt.setTimeNo(timeNo);
        tt.setUserNo(loggedInNo);
        
        if(ttDAO.delete(tt)==1) {
            JOptionPane.showMessageDialog(null, "정보가 삭제되었습니다.");
            txtSubject.setText("");
            txtProf.setText("");
            txtClassroom.setText("");
            cbxDay.setSelectedIndex(0);
            cbxStartTime.setSelectedIndex(0);
            cbxEndTime.setSelectedIndex(0);
            loadTimeTable(ttDAO.getList(loggedInNo));
        } else {
            JOptionPane.showMessageDialog(null, "정보 삭제를 실패했습니다.", "경고", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ttDAO.dbClose();
    }//GEN-LAST:event_btnDeleteSubjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSubject;
    private javax.swing.JButton btnDeleteSubject;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModifySubject;
    private javax.swing.JButton btnOverlap;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cbxDay;
    private javax.swing.JComboBox<String> cbxEndTime;
    private javax.swing.JComboBox<String> cbxStartTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelReg;
    private javax.swing.JPanel jPanelTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClassroom;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOverlap;
    private javax.swing.JLabel lblProp;
    private javax.swing.JLabel lblPw;
    private javax.swing.JLabel lblPw1;
    private javax.swing.JLabel lblPw2;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTimeTableName;
    private javax.swing.JTextField timeTableNo;
    private javax.swing.JTextField txtClassroom;
    private javax.swing.JTextField txtLoginId;
    private javax.swing.JPasswordField txtLoginPw;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtRegId;
    private javax.swing.JTextField txtRegName;
    private javax.swing.JPasswordField txtRegPw;
    private javax.swing.JPasswordField txtRegPwChk;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
